[package]
name = "tribble-app"
version = "0.1.1"
edition = "2018"
description = "The Perseus app that underlies Tribble."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/tribble"
readme = "../../README.md"
keywords = ["perseus", "template-engine"]
categories = ["template-engine", "wasm", "internationalization", "web-programming", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = "0.3.5"
sycamore = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
serde_yaml = "0.8"
web-sys = { version = "0.3", features = [ "Event", "HtmlSelectElement", "HtmlOptionElement", "Navigator", "Clipboard" ] }
wasm-bindgen = "0.2"
js-sys = "0.3"
base64 = "0.13"
wasm-bindgen-futures = "0.4"
futures = "0.3"
perseus-size-opt = "0.1"
schemars = { version = "0.8", optional = true }
pulldown-cmark = "0.8"
urlencoding = "2"

[features]
schema = [ "schemars" ]
# We need to enable the `server-side` feature for some of the exporting code to work
export = [ "perseus/server-side" ]

[[bin]]
name = "schema"
path = "src/bin/schema.rs"
required-features = [ "schema" ]
