[package]
name = "tribble-cli"
version = "0.1.0"
edition = "2021"
include = [
    "src/",
    "Cargo.toml",
    ".perseus/"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
fmterr = "0.1"
clap = { version = "=3.0.0-beta.5", features = [ "color" ] }
include_dir = "0.6"

[[bin]]
name = "tribble"
path = "src/main.rs"
