name: Build and Release

on:
    push:
        tags:
            - "v*"

jobs:
    # This builds and releases for Windows, MacOS, and Linux
    usu-build-release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: tribble
                      asset_name: tribble-linux-amd64
                    - os: macos-latest
                      artifact_name: tribble
                      asset_name: tribble-macos-amd64
                    - os: windows-latest
                      artifact_name: tribble.exe
                      asset_name: tribble-windows-amd64
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: bonnie ci prep
            - name: Build
              run: bonnie build
            - name: Release binary
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/release/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: ${{ github.ref }}
                  body: "The below binaries/executables are for the Tribble CLI. See [CHANGELOG.md](./CHANGELOG.md) for details of the changes in this version."
    # This builds and releases for musl
    musl-build-release:
        runs-on: ubuntu-latest # We cross-compile from Ubuntu
        steps:
            - uses: actions/checkout@v2
            - name: Install musl toolchain
              run: rustup target add x86_64-unknown-linux-musl
            - run: cargo install bonnie
            - run: bonnie ci prep
            - name: Build
              run: bonnie build --target x86_64-unknown-linux-musl
            - name: Release binary
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/x86_64-unknown-linux-musl/release/tribble
                  asset_name: tribble-musl-amd64
                  tag: ${{ github.ref }}
                  body: "The below binaries/executables are for the Tribble CLI. See [CHANGELOG.md](./CHANGELOG.md) for details of the changes in this version."
    # Builds the JSON schema
    build-schema:
        runs-on: ubuntu-latest # We cross-compile from Ubuntu
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            # We don't need to run the usual CI preparation for this one
            - name: Build
              run: bonnie schema
            - name: Release schema
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: schema.json
                  asset_name: tribble-schema.json
                  tag: ${{ github.ref }}
                  body: "The below binaries/executables are for the Tribble CLI. See [CHANGELOG.md](./CHANGELOG.md) for details of the changes in this version."
