name: Test

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: bonnie ci prep
            - name: Run checks
              run: bonnie check
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: bonnie ci prep
            - name: Run traditional tests
              run: cargo test --all
    # TODO Add a separate job for E2E tests (once we have them)
