name: Compile and Deploy Website

on:
    push:
        paths:
            - "packages/tribble-app/src/parser.rs" # The parser contains the API docs
            - "packages/tribble-app/bin/schema.rs" # The schema building binary should trigger re-runs
            - ".github/workflows/website.yml" # If we change this build script, it should rerun
            - "bonnie.toml" # Any changes to the `schema` commands should trigger a rebuild
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: pip install json-schema-for-humans
            - name: Build website
              run: bonnie schema && bonnie schema html
            - name: Deploy website to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/
                  publish_branch: gh-pages
