[package]
name = "tribble"
version = "0.1.0-rc.7"
edition = "2021"
include = [
    "src/",
    "Cargo.toml",
    ".tribble/"
]
description = "A CLI for generating websites to guide people through contributing to open-source projects."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/tribble"
readme = "../../README.md"
keywords = ["cli", "open-source-mgmt"]
categories = ["command-line-utilities", "development-tools", "internationalization", "web-programming", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tribble-app = { path = "../tribble-app", version = "0.1.0-rc.7" }
perseus = { version = "0.3", features = [ "server-side" ] } # We need to enable the `server-side` feature
thiserror = "1"
fmterr = "0.1"
clap = { version = "=3.0.0-beta.5", features = [ "color" ] }
include_dir = "0.6"
fs_extra = "1"
warp = "0.3"
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }
notify = "4"
